# See http://www.appveyor.com/docs/appveyor-yml for many more options

environment:
  NuGetApiKey:
    secure: QPlmSJgZZQsZS4aBjAwIIOgyZ+jTyJ01/Ox9icT7f+Tg1bbFeYcVQreMoqAb7l+7
  GitHubKey:
    secure: 5XdP6pId4p0ZveItsvG+Zv3c3Yv8kXUg3LTGh+R6er9t5sY9Bm+RRlQgMS2glZh5

skip_commits:
  message: /update version.*/

os: "WMF 5"

install:
  - ps: Write-Output "Build Number $($env:APPVEYOR_BUILD_NUMBER)"
  - ps: Write-Output "Build Version $($env:APPVEYOR_BUILD_VERSION)"

build: off

before_test:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GitHubKey):x-oauth-basic@github.com`n"
  - git config --global user.email "adam.birds@adbtechltd.co.uk"
  - git config --global user.name "Adam Birds"
  - ps: .\build.ps1

test_script:
# Test with native PS version
#  - ps: . .\Tests\appveyor.pester.ps1 -Test
# Finalize pass - collect and upload results
  - ps: . .\Tests\appveyor.pester.ps1 -Finalize

branches:
  # whitelist
  only:
    - master

#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
